name: Download adblock source list

on:
  schedule:
    - cron: 0 */12 * * *
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - name: adblock
        run: |
          echo "Downloading oisd big block list..."
          curl -s 'https://big.oisd.nl/domainswild' -o big.txt
          rm -fr oisd_big.yamle
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Automatic update
