name: Download adblock source list

on:
  schedule:
    - cron: 0 */12 * * *
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - name: Download AdBlock lists
        run: |
          echo "Downloading big adblock list..."
          curl -s 'https://big.oisd.nl/domainswild' -o oisd_big_domainswild.txt
          echo "Downloading small adblock list..."
          curl -s 'https://small.oisd.nl/domainswild' -o oisd_small_domainswild.txt
          git diff
          rm -fr oisd_big.yamle
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Automatic update
      - name: Debugging
        run: |
          echo "Files in the directory:"
          ls -l
          echo "Git status:"
          git status
