name: Download adblock source list

on:
  schedule:
    - cron: 0 */12 * * *
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      
      - name: Download AdBlock lists
        run: |
          echo "Downloading big adblock list..."
          curl -s 'https://big.oisd.nl/domainswild' -o oisd_big_domainswild.txt
          echo "Downloading small adblock list..."
          curl -s 'https://small.oisd.nl/domainswild' -o oisd_small_domainswild.txt
          
      - name: Rename files
        run: |
          mv oisd_big_domainswild.txt big.txt
          mv oisd_small_domainswild.txt small.txt
          
      - name: Clean up original files
        run: |
          rm -fr oisd_big.yamle oisd_big_domainswild.txt oisd_small_domainswild.txt
          
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Automatic update
