name: Update adblock source list

on:
  schedule:
    - cron: 0 */12 * * *
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - name: adblock
        run: |
          echo "Downloading big adblock list..."
          curl -s 'https://big.oisd.nl/domainswild' -o big.txt
          echo "Downloading small adblock list..."
          curl -s 'https://small.oisd.nl/domainswild' -o small.txt
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update source list
